/**
 *  * Universal Soul Engine
  * 地理データ、ロジックJSON、プレイヤー入力を合成して「魂（Identity）」を生成する
   */

   class SoulEngine {
     /**
        * キャラクターのスポーン（ミント）処理
           * @param {Object} geoPoint - 土地JSON（izu.json等）の特定のヘックスのattr
              * @param {Object} logic - ロジックJSON (sengoku-logic.json)
                 * @param {Object} legacyData - 前代からの引き継ぎデータ（任意）
                    * @param {Object} userPrefs - ユーザーが選択した設定（gender等, 任意）
                       */
                         static spawn(geoPoint, logic, legacyData = null, userPrefs = {}) {
                             const { attr } = geoPoint;
                                 
                                     // 1. 性別の決定
                                         const gender = this._determineAttribute(
                                               logic.generation_protocols.gender, 
                                                     userPrefs.gender
                                                         );

                                                             // 2. 年齢の決定
                                                                 const age = this._determineAge(
                                                                       logic.generation_protocols.spawn_age, 
                                                                             userPrefs.age
                                                                                 );

                                                                                     // 3. 職業の抽選（地形補正を適用）
                                                                                         const occupation = this._determineOccupation(
                                                                                               attr, 
                                                                                                     logic.spawn_probability, 
                                                                                                           logic.province_overrides[logic.province] // 地域補正があれば適用
                                                                                                               );

                                                                                                                   // 4. 行動AP補正の計算（性別 × 職業 × 遺産）
                                                                                                                       const apModifiers = this._calculateAPModifiers(
                                                                                                                             gender, 
                                                                                                                                   occupation, 
                                                                                                                                         logic, 
                                                                                                                                               legacyData
                                                                                                                                                   );

                                                                                                                                                       // 5. 最大APと学習効率（年齢数式適用）
                                                                                                                                                           const stats = this._calculateAgeStats(age, logic.trait_modifier_map.age_traits);

                                                                                                                                                               // 6. ビジュアルキーの紐付け（疎結合アセット用）
                                                                                                                                                                   const visualKey = this._getVisualKey(gender, occupation, age, logic);

                                                                                                                                                                       return {
                                                                                                                                                                             timestamp: Date.now(),
                                                                                                                                                                                   spawn_location: geoPoint.hex_id,
                                                                                                                                                                                         identity: {
                                                                                                                                                                                                 gender,
                                                                                                                                                                                                         age,
                                                                                                                                                                                                                 occupation,
                                                                                                                                                                                                                         bloodline: legacyData ? legacyData.unlocked_bloodline : "commoner"
                                                                                                                                                                                                                               },
                                                                                                                                                                                                                                     capabilities: {
                                                                                                                                                                                                                                             ap_modifiers: apModifiers,
                                                                                                                                                                                                                                                     max_ap: stats.max_ap,
                                                                                                                                                                                                                                                             learning_rate: stats.learning_rate
                                                                                                                                                                                                                                                                   },
                                                                                                                                                                                                                                                                         visual_ref: visualKey,
                                                                                                                                                                                                                                                                               legacy_status: "active"
                                                                                                                                                                                                                                                                                   };
                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                       // 重み付け抽選
                                                                                                                                                                                                                                                                                         static _weightedRandom(pool) {
                                                                                                                                                                                                                                                                                             let totalWeight = pool.reduce((sum, item) => sum + (item.weight || item.base_weight), 0);
                                                                                                                                                                                                                                                                                                 let random = Math.random() * totalWeight;
                                                                                                                                                                                                                                                                                                     for (let item of pool) {
                                                                                                                                                                                                                                                                                                           random -= (item.weight || item.base_weight);
                                                                                                                                                                                                                                                                                                                 if (random <= 0) return item.id;
                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                         return pool[0].id;
                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                             // 性別等の属性決定
                                                                                                                                                                                                                                                                                                                               static _determineAttribute(protocol, preferredValue) {
                                                                                                                                                                                                                                                                                                                                   if (protocol.input_method === "choice" && preferredValue) return preferredValue;
                                                                                                                                                                                                                                                                                                                                       return this._weightedRandom(protocol.options);
                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                           // 年齢決定
                                                                                                                                                                                                                                                                                                                                             static _determineAge(protocol, preferredValue) {
                                                                                                                                                                                                                                                                                                                                                 if (protocol.input_method === "discrete" && preferredValue && protocol.available_formats.values.includes(preferredValue)) {
                                                                                                                                                                                                                                                                                                                                                       return preferredValue;
                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                               const vals = protocol.available_formats.values;
                                                                                                                                                                                                                                                                                                                                                                   return vals[Math.floor(Math.random() * vals.length)];
                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                       // 職業決定ロジック
                                                                                                                                                                                                                                                                                                                                                                         static _determineOccupation(attr, prob, provinceOverride) {
                                                                                                                                                                                                                                                                                                                                                                             let pool = JSON.parse(JSON.stringify(prob.occupation_pool)); // ディープコピー
                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                     // 地形補正の適用
                                                                                                                                                                                                                                                                                                                                                                                         Object.values(prob.terrain_modifiers).forEach(mod => {
                                                                                                                                                                                                                                                                                                                                                                                               let match = true;
                                                                                                                                                                                                                                                                                                                                                                                                     if (mod.condition.terrain_type !== undefined && mod.condition.terrain_type !== attr.terrain_type) match = false;
                                                                                                                                                                                                                                                                                                                                                                                                           if (mod.condition.elevation_m) {
                                                                                                                                                                                                                                                                                                                                                                                                                   if (mod.condition.elevation_m.lt && attr.elevation_m >= mod.condition.elevation_m.lt) match = false;
                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                     if (match) {
                                                                                                                                                                                                                                                                                                                                                                                                                                             pool.forEach(occ => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (mod.targets.includes(occ.id)) occ.base_weight *= mod.mul;
                                                                                                                                                                                                                                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // 地域（国）補正の適用
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (provinceOverride && provinceOverride.samurai_spawn_bonus) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       pool.find(o => o.id === "samurai").base_weight *= provinceOverride.samurai_spawn_bonus;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return this._weightedRandom(pool);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // AP補正計算
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     static _calculateAPModifiers(gender, occupation, logic, legacy) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const genderBase = logic.trait_modifier_map.gender_traits[gender].ap_mult;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const occBase = logic.occupation_ap_modifiers[occupation];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     let combined = {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const allActions = new Set([...Object.keys(genderBase), ...Object.keys(occBase)]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 allActions.forEach(action => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const gMul = genderBase[action] || 1.0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const oMul = occBase[action] || 1.0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   let finalMul = gMul * oMul;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // 遺産（Legacy）による引き継ぎ補正
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (legacy && legacy.inheritance_ap_bonus) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       finalMul *= (1.0 - legacy.inheritance_ap_bonus); // 例: 0.1ボーナスならコスト0.9倍
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         combined[action] = parseFloat(finalMul.toFixed(2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return combined;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // 年齢によるステータス計算
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       static _calculateAgeStats(age, traits) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // evalの代わりに簡易的な数式解釈（実際は数式パーサーを推奨）
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const max_ap = 100 + (age * 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const learning_rate = Math.max(0.5, 1.5 - (age * 0.05));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return { max_ap, learning_rate };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           static _getVisualKey(gender, occupation, age, logic) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // 疎結合アセットJSONを引くためのキーを生成
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // 例: "m_base_samurai_13"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const genderKey = logic.trait_modifier_map.gender_traits[gender].visual_key;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return `${genderKey}_${occupation}_${age}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             export default SoulEngine;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 */